# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set image tag
      id: extract_image_tag
      run: |
        IMAGE_TAG="$(echo ${{github.ref}} | awk -F'/' '{print $NF}')"
        echo ${{ $IMAGE_TAG == 'master' && 'latest' || $IMAGE_TAG}}
